### ISSUE TITLE
Reproducing results from the paper

### ISSUE THREAD

**Issue by Sydneylsj** [VISLANG-Lab/MLGCN-DP#1]
Hi,
I'm trying to reproduce the results from the paper. 
The results that I got were quite low compared to that reported in the paper. B1% only around or below 22.24 , B2% only around or below 6.12.
I wonder what should I do to get the results reported?
Thanks a lot in advance for your valuable help.

**Comment by VILAN-Lab** [comment]
Can you show me the generated file? :)
Maybe you can try to train it with more epoch `python train.py -epoch 80`, and choose the best valid accuracy ckpt to generate. 
There is one issue in **generate_story.py** about the **punctuation**, which may have an impact on the evaluation score.  I have corrected and uploaded it, please download the new file for generation. 
I appreciate your interest in our work.

**Comment by Sydneylsj** [comment]
Thank you for your reply.
I tried to download the latest code and train it with more epoch. The best valid accuracy ckpt generated was **699_ 17.223.ckpt**.  But the BLEU value obtained is still lower than the result reported in the paper.
The file generated has been uploaded.
[generate_story.txt](https://github.com/VISLANG-Lab/MLGCN-DP/files/6090026/generate_story.txt)

**Comment by VILAN-Lab** [comment]
I can see the file **generate_story.txt** you uploaded. :)
I calculate BLEU value with your generated file, I got B1% **24.03**, B2% **8.70**. Have you got the result same with me? The B1 is lower than the result reported in the paper but the B2 is higher. (B1% **24.6**, B2% **8.6** in paper)
We can see the generated sentences is generally shorter than the sentences in reference. In this case, lower B1 (0.6 below) is acceptable. There is another thing that the sentences of the pre file and ref flie should be set to the uniform case. (lowecase recommend)
By the way, I use [nlg-eval](https://github.com/Maluuba/nlg-eval) tool for BLEU calculation.
I guess that maybe the random seed will have a little of impact on the performance of model when training.

**Comment by Sydneylsj** [comment]
I tried to use the nlg-eval tool for evaluation and have been able to reproduce the comparable results of the paper. I think the previous error may be caused by different evaluation tool. Thank you very much for your work and help.

**Comment by VILAN-Lab** [comment]
Yeah, the different evaluation tools may result in different scores, I am glad to see you got the comparable results of our paper. :)
I will try to re-run and check the code in the fulture.
Thank you again for your attention to our work.
